version: '3.7'

services:
  php:
    container_name: eval_symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"

volumes:
  data_db: